<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SFA.DAS.Recruit.Api.Data</RootNamespace>
    <AssemblyName>SFA.DAS.Recruit.Api.Data</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="16.5.1" />
    <PackageReference Include="HotChocolate.Types.OffsetPagination" Version="16.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Recruit.Api.Domain\Recruit.Api.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SFA.DAS.Recruit.Api" />
    <InternalsVisibleTo Include="SFA.DAS.Recruit.Api.UnitTests" />
  </ItemGroup>

</Project>
