<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SFA.DAS.Recruit.Contracts</RootNamespace>
    <AssemblyName>SFA.DAS.Recruit.Contracts</AssemblyName>
    <ApiContractsSwaggerJsonPath Condition="'$(Configuration)' != 'Release'">$(MSBuildThisFileDirectory)..\Recruit.Api\Recruit.Api_swagger.json</ApiContractsSwaggerJsonPath>
    <ApiContractsSwaggerJsonPath Condition="'$(Configuration)' == 'Release'">https://at-recruit-alt-api.apprenticeships.education.gov.uk/openapi/swagger.json</ApiContractsSwaggerJsonPath>
    <ApiContractsNamespace>SFA.DAS.Recruit.Contracts</ApiContractsNamespace>
    <ApiContractsOutputDirectory>$(MSBuildThisFileDirectory)Generated</ApiContractsOutputDirectory>
    <ApiContractsClientName>RecruitApi</ApiContractsClientName>
    <ApiContractsJsonLibrary>Both</ApiContractsJsonLibrary>
    <IsPackable>true</IsPackable>
    <Authors>GOV.UK Education and Skills Funding Agency (ESFA) Digital Apprenticeship Service (DAS)</Authors>
    <Description>Recruit inner API request and response for use with APIM.</Description>
    <License>https://github.com/SkillsFundingAgency/das-shared-packages/blob/master/LICENSE</License>
    <PackageProjectUrl>https://github.com/SkillsFundingAgency/das-recruit-api</PackageProjectUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SFA.DAS.ApiContracts.Build" Version="17.1.196" />
    <PackageReference Include="SFA.DAS.Apim.Shared" Version="17.1.202" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch.SystemTextJson" Version="10.0.10" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>
    
  <PropertyGroup>
      <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
</Project>
